### ISSUE TITLE
请教一个问题，谢谢

### ISSUE THREAD

**Issue by yingzui** [cckuailong/reapoc#3]
vultarget的镜像是如何让容器启动时，容器里面的服务也自启动的？是写自启动服务吗？还是别的方法？

**Comment by cckuailong** [comment]
Dockerfile中使用CMD / ENTRYPOINT命令，启动容器的时候就可以拉起服务

有一点需要注意，运行在后台的程序，容器启动后会立刻退出，这种情况我一般会在启动服务命令执行后，执行 tail -f /etc/passwd来防止容器自动退出

**Comment by yingzui** [comment]
非常感谢
